program: run/main_sweep.py
command:
  - ${env}
  - /root/miniconda3/envs/contrails/bin/python
  - ${program}
  - fit
  - --config
  - run/configs/common.yaml
  - ${args}
method: grid
parameters:
  model.init_args.library:
    distribution: constant
    value: hf
  model.init_args.architecture:
    distribution: constant
    value: upernet
  model.init_args.backbone_name:
    distribution: constant
    value: google/efficientnet-b5
  data.init_args.img_size:
    distribution: categorical
    values:
    - 256
    - 384
    - 512
    - 640
    - 768
    - 1024
