program: run/main_sweep.py
command:
  - ${env}
  - /root/miniconda3/envs/contrails/bin/python
  - ${program}
  - fit
  - --config
  - run/configs/common.yaml
  - ${args}
method: random
parameters:
  model.init_args.backbone_name:
    distribution: constant
    value: nvidia/mit-b5
  data.init_args.batch_size:
    distribution: constant
    value: 64
  trainer.accumulate_grad_batches:
    distribution: constant
    value: 1
  model.init_args.loss_name:
    distribution: categorical
    values:
    - bce=1.0+dice=0
    - bce=0.25+dice=0.75
    - bce=0.5+dice=0.5
    - bce=0.75+dice=0.25
    - bce=0+dice=1.0
  model.init_args.pos_weight:
    distribution: log_uniform_values
    min: 0.01
    max: 100.0
