program: run/main_sweep.py
command:
  - ${env}
  - /root/miniconda3/envs/contrails/bin/python
  - ${program}
  - fit
  - --config
  - run/configs/common.yaml
  - ${args}
method: grid
parameters:
  model.init_args.backbone_name:
    distribution: constant
    value: nvidia/mit-b5
  data.init_args.batch_size:
    distribution: constant
    value: 64
  trainer.accumulate_grad_batches:
    distribution: constant
    value: 1
  model.init_args.loss_name:
    distribution: categorical
    values:
    - bce=1.0
    - focal=1.0
  model.init_args.pos_weight:
    distribution: categorical
    values:
    - 99  # 0.99 in terms of focal loss
    - 2  # ~0.66 in terms of focal loss
    - 1  # 0.5 in terms of focal loss
    - 0.5  # ~0.33 in terms of focal loss
    - 0.1  # ~0.1 in terms of focal loss
    - 0.01  # ~0.01 in terms of focal loss
