program: run/main_sweep.py
command:
  - ${env}
  - /root/miniconda3/envs/contrails/bin/python
  - ${program}
  - fit
  - --config
  - run/configs/common.yaml
  - ${args}
method: grid
parameters:
  model.init_args.backbone_name:
    distribution: constant
    value: nvidia/mit-b5
  model.init_args.loss_name:
    distribution: constant
    value: focal=1.0
  model.init_args.pos_weight:
    distribution: constant
    value: 2  # ~0.66 in terms of focal loss
  data.init_args.cache_dir:
    distribution: constant
    value: "null"
  data.init_args.dataset_kwargs:
    parameters:
      band_ids:
        distribution: constant
        value: [8, 9, 10, 11, 12, 13, 14, 15, 16]
      mask_type:
        distribution: categorical
        values: 
        - voting50
        - mean
        - weighted
      conversion_type:
        distribution: categorical
        values: 
        - ash 
        - minmaxall 
        - quantilesall 
        - meanstdall
      quantize:
        distribution: categorical
        values: 
        - false
        - true
      stats_precomputed:
        distribution: categorical
        values:
        - false
        - true
