program: run/main_sweep.py
command:
  - ${env}
  - /root/miniconda3/envs/contrails/bin/python
  - ${program}
  - fit
  - --config
  - run/configs/common.yaml
  - ${args}
method: random
parameters:
  trainer.max_epochs:
    distribution: categorical
    values: 
    - 20
    - 40
    - 60
  config:
    distribution: categorical
    values: 
    - run/configs/models/convnext.yaml
    - run/configs/models/eva.yaml
    - run/configs/models/maxvit.yaml
    - run/configs/models/segformer.yaml
  model.init_args.lr:
    distribution: log_uniform_values
    min: 0.000001
    max: 0.01