trainer:
  callbacks:
    - class_path: src.utils.utils.ContrailsPredictionWriterPng
      init_args:
        output_dir: preds
        img_size: 256
        threshold: null
data:
  init_args:
    data_dirs: null
    data_dirs_test:
      - /kaggle/input/google-research-identify-contrails-reduce-global-warming/test