trainer:
  max_epochs: 8
  check_val_every_n_epoch: 1
  val_check_interval: 0.125
data:
  init_args:
    dataset_kwargs:
      band_ids: [11, 14, 15]
      mask_type: weighted
      use_not_labeled: true
      pseudolabels_path: ../data/pseudolabels/out-of-fold/npy
      conversion_type: ash
      quantize: true
      stats_precomputed: false
    cache_dir: cache_pseudolabels
    remove_pseudolabels_from_val_test: true
