trainer:
  # not_labeled_weight_divider 7.0 yields twice 
  # as many samples (~ all the original labeled samples and 
  # ~ same number of samples with PL) as in usual run
  # and max_epochs for usual run is 128
  max_epochs: 64
model:
  # redice LR w.r.t. usual run so as 
  # finetuning not training from scratch
  lr: 5e-5
data:
  init_args:
    img_size_val_test: 1024
    scale_factor: 16
    crop_uniform: discrete
    sampler_type: weighted_scale
    not_labeled_weight_divider: 7.0
    dataset_kwargs:
      band_ids: [11, 14, 15]
      mask_type: voting50
      not_labeled_mode: single
      pseudolabels_path: ./pseudolabels/in-fold/npy
      conversion_type: ash
      quantize: true
      stats_precomputed: false
    cache_dir: cache_pseudolabel
    remove_pseudolabels_from_val_test: true
