
model:
  init_args:
    tta_params: 
      aggr: mean
      n_random_replays: 0
      use_hflip: false
      use_vflip: false
      rotate90_indices: null
      scale_factors: null
      shift_params:
      - [0, 4]
      - [4, 0]
      - [4, 4]
      - [0, -8]
      - [-8, 0]
      - [-8, -8]
      - [0, 12]
      - [12, 0]
      - [12, 12]