
model:
  init_args:
    tta_params: 
      aggr: mean
      n_random_replays: 0
      use_hflip: false
      use_vflip: false
      rotate90_indices: null
      scale_factors: null
      shift_params:
      - [4, 4]
      - [8, 8]
      - [12, 12]