trainer:
  deterministic: false
  accumulate_grad_batches: 1
model:
  init_args:
    library: hf
    architecture: upernet
    backbone_name: google/efficientnet-b5
    compile: true
data:
  init_args:
    batch_size: 64
