trainer:
  deterministic: true
  accumulate_grad_batches: 1
model:
  init_args:
    backbone_name: tf_efficientnet_b7.ns_jft_in1k
    compile: true
data:
  init_args:
    batch_size: 32  # muuuch slower for 64
