trainer:
  deterministic: false
  accumulate_grad_batches: 4
model:
  init_args:
    library: hf
    architecture: mask2former
    backbone_name: facebook/mask2former-swin-base-IN21k-ade-semantic
    compile: true
data:
  init_args:
    batch_size: 16