trainer:
  deterministic: false
  accumulate_grad_batches: 8
model:
  init_args:
    library: hf
    architecture: mask2former
    backbone_name: tf_efficientnetv2_m
    compile: true
data:
  init_args:
    batch_size: 8